### ISSUE TITLE
County/State Assignment

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#334]
**Bug Description**
We have a small border issue. In the first image there are 269 points whose county FIPS code could not be inferred by a county-state lookup. Most of these points are right along the border and either the county or state name is wrong. 

For the clusters of points, this is because the WTK meta data either used a two word county name when its actually a one word name (i.e. De Kalb vs DeKalb) or vice versa (i.e. Debaca vs De Baca). This can be fixed with a point-in-polygon lookup and isn't a reV issue. 

![Screen Shot 2021-10-07 at 10 36 16 AM](https://user-images.githubusercontent.com/21287088/136431523-82b14931-8025-4563-a6dc-6c70e8ae94e3.png)

![Screen Shot 2021-10-07 at 11 02 26 AM](https://user-images.githubusercontent.com/21287088/136431543-ceda5624-cc2e-4eb6-82e0-a5f115a1a9aa.png)

![Screen Shot 2021-10-07 at 11 02 54 AM](https://user-images.githubusercontent.com/21287088/136431627-b6cf5a60-26a5-45a1-abd0-ffc224e72c37.png)

**Expected behavior**
County and state pairs are assigned correctly. I'm not sure if we are assigning them according to the centroid of the full supply-curve cell or that of the un-excluded area, but either way they should match up.

**System (please complete the following information):**
 - OS: Linux
 - Compute hardware: Eagle
 - Version: 0.5.9

**Comment by grantbuster** [comment]
@WilliamsTravis I mayyyy have found out why this happens. We take the mode of the states and counties independently, so if there is a tie, you can end up with mismatched state+county combinations. The scipy mode function appears to take the alphabetically sorted first value although I'm not 100% confident in that. In either case, this is now breaking some tests (possibly due to a new scipy version?) so i'll try and fix it so that in the case of a tie you get a sensible state+county combo. 

```
In [1]: from scipy import stats

In [6]: stats.mode(['xhartley', 'hartley'])
Out[6]: ModeResult(mode=array(['hartley'], dtype='<U8'), count=array([1]))

In [7]: stats.mode(['nm', 'tx'])[0]
Out[7]: array(['nm'], dtype='<U2')

**Comment by WilliamsTravis** [comment]
Ah, yes that would make sense. Sounds great!

**Comment by WilliamsTravis** [comment]
Excellent! This has a been a minor, but pesky, little bug for some time now.

**Comment by grantbuster** [comment]
Totally, i cant guarantee that this will fix everything but i saw basically the same bug pop up on the testing end and this should fix it

**Comment by WilliamsTravis** [comment]
Gotcha, I'll keep an eye out for it then...if everything isn't fixed, we can always rely on our modal county fips characterization, so it's not urgent.

**Comment by grantbuster** [comment]
Closing as per PR #381 and release https://github.com/NREL/reV/releases/tag/v0.6.6

**Comment by WilliamsTravis** [comment]
This bug has returned!

**Comment by grantbuster** [comment]
omg haha noooo. @WilliamsTravis can you provide some resources to debug this? Code/config to reproduce and a charge code?

**Comment by MRossol** [comment]
Charge code... don't miss that...
